### ISSUE TITLE
Infer Maven artifact coordinates from context before delegating to mapping rule

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-cbi/p2repo-aggregator#8]
This is 1 solution to https://github.com/eclipse-platform/eclipse.platform.releng/issues/50 .
Currently, this aggregator applies mapping rules to derive Maven artifact coordinates from a given p2 artifact. However, as Eclipse projects now consume more directly Maven artifacts and Tycho annotate metadata with Maven coordinates, a more accurate GAV can often be deduced from the context without involving the mapping definition. Typically some content in the jar under `META-INF/maven/pom.xml` or in p2 metadata properties `maven.groupId`/`maven-artifactId`/`maven-version` can be used. The mapping rule being a last resort approach.

**Comment by merks** [comment]
With regard to the metadata properties, typically all the IUs have such properties:

![image](https://user-images.githubusercontent.com/208716/176512174-0309bcfa-80bc-43f8-bc46-67eb0dc0a551.png)

![image](https://user-images.githubusercontent.com/208716/176512299-5d8b78dc-3d57-44f9-9966-810cc054712f.png)

![image](https://user-images.githubusercontent.com/208716/176512420-8dcfe27b-027a-42ca-859b-6012d7d7eb75.png)

Might it be the case that one specifies mapping rules yet none ever get applied because of this approach?

**Comment by merks** [comment]
I see this, for example, where the group ID is `org.eclipse.ant`:

![image](https://user-images.githubusercontent.com/208716/176647276-61b67615-6858-4e71-accd-ee2526a7effc.png)

But in the  EMF.aggr I see the mapping rule specifies `org.eclipse.platform`:

![image](https://user-images.githubusercontent.com/208716/176647708-dc796775-ee68-4037-8dcc-dbc7e29692ef.png)

It appears to me that primarily using the p2's maven metadata properties and ignoring the mapping rules because they are only considered if the metadata isn't present will definitely break the result.   I don't want publishing EMF's next release to Maven not to work on the 1st shot...

**Comment by mickaelistria** [comment]
Ideally, we should work also on platform side so it uses the same groupId natively as what's expected to be published.

**Comment by merks** [comment]
It would be ideal of course if we could trust the p2 metadata.  Is there any control over these details in Tycho?  Alternatively (or in combination) we might introduce a new property that says "this is for sure the correct maven metadata for this IU".  In addition, we might always look at the rules too and then fail if they are in conflict, or extend the rule API so it can specify, "I am an override of the maven metadata because they're not accurate"...

**Comment by mickaelistria** [comment]
I've reworked related PR. The mapping rule still have priority over embedded metadata.

**Comment by mickaelistria** [comment]
Done with https://github.com/eclipse-cbi/p2repo-aggregator/pull/9
